---
- name: Config
  hosts: localhost
  connection: local
  become: true # sudo
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - git
          - gcc

    - name: Install cli programs
      ansible.builtin.package:
        name:
          - fzf
          - stow

    - name: Install latest neovim
      ansible.builtin.get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
        dest: "{{ lookup('env', 'HOME') }}/.local/bin/nvim"
        mode: "0755"

    - name: Check if Rustup is installed
      ansible.builtin.command: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup --version"
      register: rustup_check
      ignore_errors: true
      changed_when: false
      tags:
        - rust

    # - name: Debug output of rustup_check
    #   ansible.builtin.debug:
    #     var: rustup_check

    - name: Install Rustup if not installed
      ansible.builtin.command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      when: rustup_check is not defined
      register: rustup_install_output
      changed_when: false
      tags:
        - rust

    - name: Print installation output
      ansible.builtin.debug:
        msg: "{{ rustup_install_output.stdout }}"
      when: rustup_install_output is defined and rustup_install_output.stdout is defined
      tags:
        - rust

    - name: Install rust CLIs
      when: rustup_check is defined
      ansible.builtin.command:
        argv:
          - "{{ lookup('env', 'CARGO_HOME') }}/bin/cargo"
          - "install"
          - "eza"
          - "fd-find"
          - "hyperfine"
          - "feroxbuster"
      changed_when: false

    - name: Download uv installer
      ansible.builtin.get_url:
        url: "https://astral.sh/uv/install.sh"
        dest: "/tmp/uv-installer.sh"
        mode: "0777"
      changed_when: false
      tags:
        - python

    - name: Install uv
      ansible.builtin.shell: /tmp/uv-installer.sh
      changed_when: false
      tags:
        - python
