---
- name: Check if Brave Browser is installed
  ansible.builtin.command: "brave-browser --version"
  register: brave_browser_check
  ignore_errors: true
  changed_when: false

- name: Determine if installation is needed
  ansible.builtin.set_fact:
    install_brave_browser: "{{ brave_browser_check.rc != 0 }}"

- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present
  become: true
  when: install_brave_browser

- name: Download Brave Browser keyring
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: "0644"
  become: true
  when: install_brave_browser

- name: Add Brave Browser repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    mode: "0644"
    create: true
  become: true
  when: install_brave_browser

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: install_brave_browser

- name: Install or update Brave Browser
  ansible.builtin.apt:
    name: brave-browser
    state: present
  become: true
  when: install_brave_browser
